import OPERACION

print ("SUMA DE DOS NUMEROS")
OPERACION.suma()

print ("RESTA DE DOS NUMEROS")
OPERACION.resta()

print ("MULTIPLICACION DE DOS NUMEROS")
OPERACION.mult()

print ("DIVISION DE DOS NUMEROS")
OPERACION.div()

print ("SERIE DE FIBONACCI")
OPERACION.fib(25)